---
- name: Création du répertoire d'installation
  win_file:
    path: C:\ProgramData\NXLog
    state: directory

- name: Déploiement de la configuration NXLog
  win_template:
    src: nxlog.conf.j2
    dest: C:\ProgramData\NXLog\nxlog.conf
  notify: restart nxlog

- name: Vérification de la présence de Sysmon
  win_stat:
    path: C:\Windows\Sysmon\sysmon.exe
  register: sysmon_check

- name: Déploiement de la configuration Sysmon
  win_template:
    src: sysmon-config.xml
    dest: C:\ProgramData\Sysmon\sysmon-config.xml
  when: sysmon_check.stat.exists

- name: Démarrage du service NXLog
  win_service:
    name: NXLog
    state: started
    start_mode: auto
  ignore_errors: yes
