---
- name: Mise à jour des paquets OPNsense
  shell: pkg update && pkg upgrade -y
  changed_when: false

- name: Vérification de l'état du pare-feu
  shell: pfctl -si | head -20
  register: pf_status
  changed_when: false

- name: Afficher le statut du pare-feu
  debug:
    var: pf_status.stdout_lines
