[opnsense]
opnsense ansible_host=10.0.1.1 ansible_user=root ansible_connection=ssh

[linux_servers]
soc         ansible_host=10.0.1.10 ansible_user=vagrant ansible_become=true
debian-server ansible_host=10.0.1.20 ansible_user=vagrant ansible_become=true

[windows]
windows10   ansible_host=10.0.1.30 ansible_user=vagrant ansible_connection=winrm ansible_winrm_server_cert_validation=ignore

[all:vars]
ansible_python_interpreter=/usr/bin/python3
