# Global parameters
[global]
	dns forwarder = 10.0.1.1
	netbios name = SRV-PME
	realm = NYX.TG
	server role = active directory domain controller
	workgroup = NYX
	idmap_ldb:use rfc2307 = yes

[sysvol]
	path = /var/lib/samba/sysvol
	read only = No

[netlogon]
	path = /var/lib/samba/sysvol/nyx.tg/scripts
	read only = No

# PARTAGES PME (ajoutés pour le laboratoire Nyx)

[direction]
   path = /srv/samba/direction
   valid users = @NYX\direction
   read only = no
   create mask = 0660
   directory mask = 2770
   force group = direction
   browseable = yes
   comment = Documents confidentiels - Direction

[comptabilite]
   path = /srv/samba/comptabilite
   valid users = @NYX\comptabilite
   read only = no
   create mask = 0660
   directory mask = 2770
   force group = comptabilite
   browseable = yes
   comment = Relevés financiers - Comptabilité

[technique]
   path = /srv/samba/technique
   valid users = @NYX\technique
   read only = no
   create mask = 0660
   directory mask = 2770
   force group = technique
   browseable = yes
   comment = Configurations et scripts - Technique

[commun]
   path = /srv/samba/commun
   valid users = @NYX\direction @NYX\comptabilite @NYX\technique
   read only = no
   create mask = 0664
   directory mask = 2777
   force group = domain\ users
   browseable = yes
   comment = Zone d'échange transversale
