# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.4.9"

Vagrant.configure("2") do |config|
  # Provider par défaut pour toutes les VMs
  config.vm.provider "libvirt" do |libvirt|
    libvirt.driver = "kvm"
    libvirt.uri = "qemu:///system"
    libvirt.qemu_use_agent = false
    libvirt.cpus = 1
    libvirt.memory = 1024
  end

  # SOC (Debian 12) 
  config.vm.define "soc" do |soc|
    soc.vm.box = "debian-12"
    soc.vm.provider "libvirt" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    soc.vm.network "private_network",
      ip: "10.0.1.10",
      netmask: "255.255.255.0",
      libvirt__network_name: "nyx",
      libvirt__forward_mode: "none"
  end

  # Debian Server (Samba AD + Dolibarr)
  config.vm.define "debian-server" do |server|
    server.vm.box = "debian-12"
    server.vm.provider "libvirt" do |vb|
      vb.memory = 3072 # 3 gigas octets
      vb.cpus = 2
      vb.machine_virtual_size = 30
    end
    server.vm.network "private_network",
      ip: "10.0.1.20",
      netmask: "255.255.255.0",
      libvirt__network_name: "nyx",
      libvirt__forward_mode: "none"
    server.vm.provision "shell", inline: <<-SHELL
      ROOT_DEV=$(findmnt -n -o SOURCE /)
      if [[ "$ROOT_DEV" =~ ^/dev/(sd[a-z]|vd[a-z]|nvme[0-9]n[0-9])p?([0-9]+)$ ]]; then
          DISK="/dev/${BASH_REMATCH[1]}"
          PART="${BASH_REMATCH[2]}"
          echo "Resizing root partition on $DISK $PART..."
          apt-get update && apt-get install -y cloud-guest-utils
          growpart "$DISK" "$PART" || true
          resize2fs "$ROOT_DEV" || true
      else
          echo "Could not parse root device: $ROOT_DEV"
      fi
    SHELL
  end

  # Windows 10
  config.vm.define "windows10" do |win|
    win.vm.box = "windows-10"
    win.vm.provider "libvirt" do |vb|
      vb.memory = 3072
      vb.cpus = 2
    end
    win.vm.network "private_network",
      ip: "10.0.1.30",
      netmask: "255.255.255.0",
      libvirt__network_name: "nyx",
      libvirt__forward_mode: "none"
    
    # Désactiver le dossier partagé par défaut pour éviter l'erreur NFS sur Windows
    win.vm.synced_folder ".", "/vagrant", disabled: true

    # Pour Windows, utiliser WinRM au lieu de SSH
    win.vm.communicator = "winrm"
    win.winrm.username = "vagrant"
    win.winrm.password = "vagrant"
    win.winrm.max_tries = 300
    win.winrm.retry_delay = 5
    win.vm.boot_timeout = 600
  end

  # Provisionnement Ansible global
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible/playbooks/site.yml"
    ansible.inventory_path = "ansible/inventory.ini"
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
    ansible.groups = {
      "linux_servers" => ["soc", "debian-server"],
      "windows" => ["windows10"]
    }
  end
end